twig.path: "%root_dir%/src/Placephant/Resources/views"
http_cache.cache_dir: "%root_dir%/app/cache/http"
routing.resource: "%root_dir%/app/config/routing.yml"
routing.options:
    cache_dir: "%root_dir%/app/cache/routing"

config:
  name: "placephant"
  url: "http://placephant.com"
  title: "PlacePhant - an image placeholder featuring elephpants"
  description: "A Simple placeholder service for the PHP lovers out there, featuring lovely elephpants."
  resources: "%root_dir%/src/Placephant/Resources/images"
  max_width: 2500
  max_height: 2500

