twig.path: "%root_dir%/src/Placephant/Resources/views"
routing.resource: "%root_dir%/app/config/routing.yml"

debug: true

config:
  name: "placephant"
  url: "http://placephant.com"
  title: "PlacePhant - an image placeholder featuring elephpants"
  description: "A Simple placeholder service for the PHP lovers out there, featuring lovely elephpants."
  resources: "%root_dir%/src/Placephant/Resources/images"
